name: SmartInvs
version: 1.3.5
description: Inventory API for your Bukkit Plugins.
author: MinusKube
website: https://github.com/MinusKube/SmartInvs
main: fr.minuskube.inv.SmartInvsPlugin
folia-supported: false